### ISSUE TITLE
Request: randomize button

### ISSUE THREAD

**Issue by Demitrix2k** [snorpey/jpg-glitch-electron#4]
First of all thank you for this great tool, been enjoying it.
Your online version has a randomize button
https://snorpey.github.io/jpg-glitch/

Any chance the electron version for Windows could also have it, or perhaps i have yet to find it?
![w10](https://user-images.githubusercontent.com/38674952/79780956-064a5580-833d-11ea-9a60-0236e8917ee5.jpg)

**Comment by snorpey** [comment]
@Demitrix2k thank you for using the tool, i'm glad you like it.

that's is a good point, i think i just forgot adding the rendomize button when porting it to electron. i'll add it as soon as i can!

**Comment by snorpey** [comment]
hey @Demitrix2k

i just added the random button.

you can download the latest version here:
https://github.com/snorpey/jpg-glitch-electron/releases/tag/v0.1.3

let me know if it works for you!

**Comment by Demitrix2k** [comment]
Awesome, thank you so much!
Seems to work just like on the website version.
